import streamlit as st
from ultralytics import YOLO
from PIL import Image, ImageOps
import numpy as np
import cv2
import gc
import os
from core_rag import ask_question 
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = Path(os.getenv("YOLO_MODEL_PATH", BASE_DIR / "models" / "best.pt"))

# ==========================================
# 1. INITIALIZATION & MEMORY SAVERS
# ==========================================
st.set_page_config(page_title="Caltrans Assistant v4", layout="wide")
st.title("🚧 Caltrans Utility AI Assistant")

# Caltrans district context
st.sidebar.markdown("---")
st.sidebar.header("📍 Caltrans Context")

selected_district = st.sidebar.selectbox(
    "Select Caltrans District:",
    [f"District {i}" for i in range(1, 13)],
    index=10,  # District 11
    help="Sets the Caltrans district context for text queries and photo analysis."
)
         

# Load the YOLO model once and cache it.
@st.cache_resource
def load_yolo_model():
    # Force Python to clear out dead memory blocks before loading the model
    gc.collect() 
    model = YOLO(MODEL_PATH)
    return model


# ============================================================
# GENERAL ENGINEERING REPORT GENERATOR
# ============================================================

def generate_markdown_report(
    mode,
    query,
    answer,
    sources,
    s77_spec=None,
    district=None,
    owner=None,
    unit_rate=None,
    quantity=None,
    payment_unit=None,
    contingency=None,
    total_cost=None
):
    """Generate a downloadable Markdown engineering report.

    Works for both:
    - Standalone Manual Lookup
    - Section 77 Drafting Wizard
    """

    report = f"""# CALTRANS ENGINEERING REPORT

**Assistant Mode:** {mode}  
**District Context:** {district or "N/A"}  
**Asset / Work Item:** {query}

---

## 1. ENGINEERING CONTEXT

**Selected Utility Owner:** {owner or "N/A"}  
**Selected Asset / Work Item:** {query}

"""

    # --------------------------------------------------------
    # S77 PROJECT ESTIMATE
    # --------------------------------------------------------

    if any(value is not None for value in [
        unit_rate,
        quantity,
        payment_unit,
        contingency,
        total_cost
    ]):

        report += f"""### Preliminary Engineering Cost Estimate

**Unit Rate:** ${unit_rate:,.2f}  
**Quantity:** {quantity} {payment_unit or ""}  
**Mobilization & Contingency (10%):** ${contingency:,.2f}  
**Total Preliminary Estimate:** **${total_cost:,.2f}**

> This estimate is intended for preliminary engineering and Right-of-Way
> Data Sheet planning. Final contract quantities, bid items, and costs
> require project-specific verification.

---

"""

    # --------------------------------------------------------
    # S77 SPECIAL PROVISIONS
    # --------------------------------------------------------

    if s77_spec:

        report += """## 2. GENERATED SECTION 77 SPECIAL PROVISIONS

"""

        report += s77_spec

        report += """

---

"""

    # --------------------------------------------------------
    # ENGINEERING DIRECTIVE / FINDING
    # --------------------------------------------------------

    report += """## ENGINEERING DIRECTIVE / FINDING

"""

    report += f"{answer}"

    report += """

---

## VERIFIED REFERENCE MATERIALS

"""

    # --------------------------------------------------------
    # REFERENCES
    # --------------------------------------------------------

    if sources:

        for src in sources:
            report += (
                f"- **Manual:** {src.get('source_manual', 'N/A')}  \n"
                f"  **Section:** {src.get('section', 'N/A')}  \n"
                f"  **Page:** {src.get('page', 'N/A')}  \n\n"
            )

    else:

        report += "*No retrieved reference materials were recorded.*\n\n"

    # --------------------------------------------------------
    # ENGINEER VERIFICATION
    # --------------------------------------------------------

    report += """---

## ENGINEER VERIFICATION ITEMS

The generated material is a drafting and engineering
decision-support aid. Review against the applicable project
plans, contract documents, Caltrans Standard Specifications,
Standard Plans, current manuals, and project-specific
requirements.

Verify, as applicable:

- Applicable Caltrans specification sections
- Final contract bid item number and description
- Final quantity and measurement unit
- Project-specific construction requirements
- Utility owner requirements
- Required permits, agreements, and approvals
- Plan and U-Sheet requirements
- Final measurement and payment provisions
- Project-specific utility clearances and conflicts

---

*Generated by Caltrans Assistant — Engineering Decision Support System*
"""

    return report


# Supplemental engineering notes
def get_engineering_note(asset_class):
    """Return the supplemental engineering note applicable to a detected asset."""

    try:
        with open("reference/engineering_notes.txt", "r", encoding="utf-8") as f:
            notes = f.read()

        normalized_asset = asset_class.strip().lower()

        # Find each ASSET section
        asset_positions = []
        search_start = 0

        while True:
            position = notes.find("ASSET:", search_start)

            if position == -1:
                break

            asset_positions.append(position)
            search_start = position + len("ASSET:")

        # Examine each ASSET section
        for i, start in enumerate(asset_positions):

            # End at the next ASSET section
            if i + 1 < len(asset_positions):
                section = notes[start:asset_positions[i + 1]]
            else:
                section = notes[start:]

            # Find APPLIES TO line
            applies_line = next(
                (
                    line.strip()
                    for line in section.splitlines()
                    if line.strip().upper().startswith("APPLIES TO:")
                ),
                ""
            )

            if not applies_line:
                continue

            # Get listed YOLO classes
            applicable_assets = applies_line.split(":", 1)[1]

            asset_list = [
                asset.strip().lower()
                for asset in applicable_assets.split(",")
            ]

            # Does this note apply to the detected asset?
            if normalized_asset in asset_list:

                # Remove ASSET and APPLIES TO metadata
                note_lines = []

                for line in section.splitlines():

                    stripped = line.strip()

                    if stripped.upper().startswith("ASSET:"):
                        continue

                    if stripped.upper().startswith("APPLIES TO:"):
                        continue

                    if stripped.startswith("----------------------------------------"):
                        continue

                    note_lines.append(line)

                return "\n".join(note_lines).strip()

        return ""

    except FileNotFoundError:
        return ""

# ==========================================
# 2. APP MODE SELECTOR
# ==========================================
app_mode = st.radio(
    "Choose Assistant Mode:", 
    ["📚 Standalone Manual Lookup incl SOP (Text)", "📸 Automated Field Photo Scanner (Image)"],
    horizontal=True
)

# ==========================================
# MODE A: STANDALONE TEXT RETRIEVAL
# ==========================================
if app_mode == "📚 Standalone Manual Lookup incl SOP (Text)":
    
    # --- S77 WIZARD TOGGLE FIRST ---
    activate_s77_wizard = st.toggle("📋 Activate Section 77 Special Provisions Drafting Wizard", value=False)
    st.markdown("---")

    if "standard_answer" not in st.session_state:
        st.session_state.standard_answer = None

    if "standard_sources" not in st.session_state:
        st.session_state.standard_sources = []

    if "standard_query" not in st.session_state:
        st.session_state.standard_query = None

    if "s77_draft" not in st.session_state:
        st.session_state.s77_draft = None

    if "s77_references" not in st.session_state:
        st.session_state.s77_references = []

    if "s77_estimate" not in st.session_state:
        st.session_state.s77_estimate = None

    # BRANCH 1: STANDARD MANUAL LOOKUP (Only shows when Wizard is OFF)
    if not activate_s77_wizard:
        st.subheader("🔍 Query Caltrans & SOP Manuals Directly")
        user_query = st.text_input(
            "Type your engineering or utility question here...", 
            placeholder=f"e.g., What are the clearance requirements in {selected_district}?"
        )
        
        if user_query:
            st.markdown("### 🔍 Manual Lookup Profile")
            st.write(f"Ready to search standard SOP database using **{selected_district}** clearance baselines.")
            
            submit_standard = st.button("🔍 Search Manuals & SOPs")
                
            if submit_standard:
                with st.spinner("Searching manuals and generating directive..."):
                    answer, sources = ask_question(
                        user_query,
                        k=5,
                        district=selected_district
                    )

                st.session_state.standard_query = user_query
                st.session_state.standard_answer = answer
                st.session_state.standard_sources = sources

            if (
                st.session_state.standard_answer
                and st.session_state.standard_query == user_query
            ):
                st.markdown("### 📝 Engineering Directive")
                st.info(st.session_state.standard_answer)

                sources = st.session_state.standard_sources

                if sources:
                    st.markdown("### 🔍 Verified References")

                    for src in sources:
                        manual = src.get("source_manual", "N/A")
                        section = src.get("section", "N/A")
                        page = src.get("page", "N/A")

                        st.markdown(
                            f"**{manual}**  \n"
                            f"Section: {section}  \n"
                            f"Page: {page}"
                        )
                    
                    st.markdown("---")
                    text_report = generate_markdown_report("Standalone Manual Lookup", user_query, st.session_state.standard_answer, sources)
                    st.download_button(
                        label="📥 Download Engineering Report (.md)",
                        data=text_report,
                        file_name=f"caltrans_{selected_district.replace(' ', '_')}_report.md",
                        mime="text/markdown"
                    )

    # BRANCH 2: THE S77 DRAFTING WIZARD (Hides the text box, relies 100% on dropdowns)
    elif activate_s77_wizard:
        st.subheader("📋 Section 77 Special Provisions Drafting Wizard")

        # Load the options structure from your external JSON configuration file
        with open(BASE_DIR / "wizard_config.json", "r", encoding="utf-8") as f:
            config = json.load(f)
        
        # ROW 1: General Project Information
        c1, c2 = st.columns(2)
        with c1:
            # This dropdown now acts as the primary asset lock—no manual typing required!
            selected_asset = st.selectbox("Confirm Specific Target Asset:", config["asset_types"])
        with c2:
            selected_owner = st.selectbox("Select Operating Utility Agency/Owner:", config["utility_owners"])
            
        # ROW 2: Technical Specifications & Billing Metrics
        c3, c4, c5 = st.columns(3)
        with c3:
            selected_material = st.selectbox("Select Material Base:", config["pipe_materials"])
        with c4:
            selected_diameter = st.selectbox("Dimension / Diameter Class:", config["pipe_diameters"])
        with c5:
            selected_scope = st.selectbox("Operational Scope of Work:", config["work_scopes"])
        
        # ROW 3: Advanced Engineering Variables & Quantities
        st.markdown("**🛠️ Engineering Overrides & Quantity Inputs:**")
        cc1, cc2, cc3 = st.columns(3)
        with cc1:
            selected_payment = st.selectbox("Primary Bid Item Payment Unit:", config["payment_methods"])
        with cc2:
            input_qty = st.number_input(f"Enter Proposed Quantity (matching {selected_payment}):", min_value=1.0, value=10.0, step=1.0)
        with cc3:
            has_casing = st.checkbox("Utility Crossing Requires Outer Protective Casing / Sleeve", value=False)
            is_recycled = st.checkbox("System Carries Recycled / Purple Pipe Non-Potable Water", value=False)
            
        st.write(f"Drafting contract framework using **{selected_district}** parameters.")
        st.markdown("---")
        
        submit_draft = st.button("🚀 Generate Comprehensive Contract Draft & Estimate")
            
        if submit_draft:
            base_unit_rate = config["standard_rates"].get(selected_asset, 0.0)
            
            if has_casing:
                base_unit_rate *= 1.25
                
            subtotal_cost = base_unit_rate * input_qty
            contingency_fee = subtotal_cost * 0.10
            total_estimated_project_cost = subtotal_cost + contingency_fee
            
            casing_string = "REQUIRED (Include carrier pipe spacers, end seals, sand backfill, and separate bid item processing for steel casing sleeve)." if has_casing else "NOT REQUIRED"
            water_type_string = "Recycled / Non-Potable Water System (Incorporate Purple Pipe identification, warning tapes, and specific environmental separation rules)." if is_recycled else "Potable Water / Standard Sewer Infrastructure"
            
            # FIXED: Removed the redundant 'user_query' variable and replaced it completely with 'selected_asset'
            
            with open("prompts/s77_prompt.txt", "r", encoding="utf-8") as f:
                s77_prompt = f.read()

       
            s77_query = f"""
   
            Context Parameters:
            - Primary Asset Classification: {selected_asset}
            - Operational Scope of Work: {selected_scope}
            - Specific Material: {selected_material}
            - Dimension / Size: {selected_diameter}
            - Operating Utility Owner / Agency: {selected_owner}
            - Caltrans District: {selected_district}
            - Primary Bid Item Payment Method: Per {selected_payment}
            
            Engineering Overrides:
            - Protective Casing/Sleeve: {casing_string}
            - Utility Stream Classification: {water_type_string}
            
            {s77_prompt}
                           
            """
            
            with st.spinner("Drafting regional S77 contract language from boilerplate references..."):
                s77_draft, references = ask_question(s77_query, k=7, district=selected_district)

            st.session_state.s77_draft = s77_draft
            st.session_state.s77_references = references
            st.session_state.s77_estimate = {
                "base_unit_rate": base_unit_rate,
                "input_qty": input_qty,
                "selected_payment": selected_payment,
                "contingency_fee": contingency_fee,
                "total_estimated_project_cost": total_estimated_project_cost,
                "selected_asset": selected_asset,
                "selected_owner": selected_owner,
                "selected_district": selected_district
            }

         # Display the most recently generated S77 result.
        # Stored in session_state so it survives Streamlit reruns
        # caused by the Download button.
        if st.session_state.s77_draft:

            s77_draft = st.session_state.s77_draft
            references = st.session_state.s77_references
            estimate = st.session_state.s77_estimate

            st.markdown("### 📊 Initial Engineer's Cost Estimate")

            ec1, ec2, ec3, ec4 = st.columns(4)

            ec1.metric(
                label="Unit Rate",
                value=f"${estimate['base_unit_rate']:,.2f}"
            )

            ec2.metric(
                label="Quantity Input",
                value=f"{estimate['input_qty']} "
                       f"{estimate['selected_payment'].split()[-1]}"
            )

            ec3.metric(
                label="10% Mobilization & Buffer",
                value=f"${estimate['contingency_fee']:,.2f}"
            )

            ec4.metric(
                label="Total Proposed Budget",
                value=f"${estimate['total_estimated_project_cost']:,.2f}"
            )

            st.markdown("### 📝 Generated Section 77 Contract Draft")
            st.markdown(s77_draft)

            if references:
                st.markdown("### 🔍 Reference Materials Ingested for Draft")

                for src in references:
                    if src.get("document_id", "N/A") != "N/A":
                        st.caption(
                            f"• **SOP:** {src.get('document_id')} | "
                            f"**Source:** {src.get('source_manual', 'N/A')} | "
                            f"**Section:** {src.get('section', 'N/A')} | "
                            f"**Page:** {src.get('page', 'N/A')}"
                        )
                    else:
                        st.caption(
                            f"• **Manual:** {src.get('source_manual', 'N/A')} | "
                            f"**Section:** {src.get('section', 'N/A')} | "
                            f"**Page:** {src.get('page', 'N/A')}"
                        )

            st.markdown("---")

            final_text_report = generate_markdown_report(
                mode="S77 Drafting Wizard",
                query=estimate["selected_asset"],
                answer=(
                    f"Contract language generated for "
                    f"{estimate['selected_owner']} - "
                    f"{estimate['selected_asset']}."
                ),
                sources=references,
                s77_spec=s77_draft,
                district=estimate["selected_district"],
                owner=estimate["selected_owner"],
                unit_rate=estimate["base_unit_rate"],
                quantity=estimate["input_qty"],
                payment_unit=estimate["selected_payment"],
                contingency=estimate["contingency_fee"],
                total_cost=estimate["total_estimated_project_cost"]
            )

            st.download_button(
                label="📥 Download Complete S77 Engineering Report (.md)",
                data=final_text_report,
                file_name=(
                    f"S77_Draft_"
                    f"{estimate['selected_district'].replace(' ', '_')}.md"
                ),
                mime="text/markdown"
            )

# ==========================================
# MODE B: AUTOMATED PHOTO SCANNER
# ==========================================
else:
    st.sidebar.header("📁 Data Input")
    # Detection settings
    confidence_threshold = st.sidebar.slider("YOLO Confidence Threshold", 0.10, 1.00, 0.35)

    # 1. Let the user choose their method on the main screen
    image_source = st.radio(
        "Select Image Input Method:",
        ["📁 Upload Image File", "📷 Use Live Device Camera"],
        horizontal=True
    )
    
    # 2. Point both options to your existing 'uploaded_file' variable
    uploaded_file = None
    if image_source == "📁 Upload Image File":
        uploaded_file = st.file_uploader("Upload a Street/Field Image...", type=["jpg", "jpeg", "png"])
    elif image_source == "📷 Use Live Device Camera":
        uploaded_file = st.camera_input("Take a snapshot of the field asset")

    # Process the uploaded image
    if uploaded_file is not None:
        col1, col2 = st.columns(2)
        
        # Memory-efficient image loading (reduces raw resolution overhead)
        raw_image = Image.open(uploaded_file)
        
        # Fix auto-rotation orientation (keeps portrait images upright)
        image = ImageOps.exif_transpose(raw_image)
        
        if image.width > 1200:
            image.thumbnail((1200, 1200)) # Downsamples massive smartphone images to save RAM
        img_array = np.array(image)
        
        # Initialize an empty list for detected classes to prevent scope errors
        detected_classes = []
        has_results = False
        
        # --- PANEL 1: OBJECT DETECTION ---
        with col1:
            st.subheader("📸 Automated Asset Detection")
            with st.spinner("Scanning image..."):
                model = load_yolo_model()
                
                # Convert RGB to BGR before feeding to YOLO so its internal logic expects standard BGR
                img_array_bgr = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
                results_list = model.predict(source=img_array_bgr, conf=confidence_threshold, device='cpu') 
                
                if results_list and len(results_list) > 0:
                    results = results_list[0]
                    has_results = True
                    
                    # Force YOLO to plot, then immediately flip back to RGB
                    annotated_img = results.plot()  
                    annotated_img_rgb = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)
                    
                    st.image(annotated_img_rgb, use_container_width=True)
                else:
                    st.warning("YOLO engine returned an empty response slice.")
                
        # --- PANEL 2: AUTOMATED ASSET, OWNER, & DISTRICT INTELLIGENCE ---

        with col2:
            st.subheader("📚 Caltrans Manual & Owner Asset Intelligence")
            

            if has_results and results.boxes is not None:
                for box in results.boxes:
                    class_id = int(box.cls)
                    class_name = model.names[class_id]
                    if class_name not in detected_classes:
                        detected_classes.append(class_name)
                    
            if detected_classes:
                st.success(f"Detected {len(detected_classes)} asset types!")
                selected_class = st.selectbox("Select an asset type to view Caltrans Guidelines:", detected_classes)
                has_target = True
            else:
                st.warning("⚠️ No specific utility assets detected above the specified threshold.")
                manual_override = st.text_input("💡 Asset type not detected? Type the asset name manually to force an intelligence lookup:", placeholder="e.g., fire_hydrant")
                if manual_override:
                    selected_class = manual_override.strip().lower()
                    has_target = True
                else:
                    has_target = False
            
            if has_target:
                supplemental_note = get_engineering_note(selected_class)
                # Utility owner context
                utility_owner = st.selectbox(
                    "Identify Asset Owner / Franchise Holder (Optional context for proprietary rules):",
                    ["General / Unknown Owner", "SDG&E (San Diego Gas & Electric)", "AT&T California", "COX", "SPECTRUM", "Municipal (City/County)", "IID", "County of San Diego", "SDWCA", "Other Utility Owner"]
                )
                
                # Plans Preparation Manual guidance
                st.markdown("---")
                with st.expander("📝 Plans Preparation Manual (PPM) Drafting Guidelines", expanded=False):
                    st.caption("ℹ️ Cross-referenced from Caltrans PPM Section 2-2.18: Utility Sheets (U-Sheets)")
                    st.markdown(
                        f"""
                        *   **U-Sheet Linework:** Existing `{selected_class}` facilities must be drawn in a screen/dashed light weight. Proposed utility installations or modifications must be drawn in a solid, bold black line weight.
                        *   **Asset Labels:** Clearly label the asset owner name, franchise agreement number, status (To Be Relocated, Protect in Place, or Abandoned), and diameter/material if subsurface.
                        *   **Reference Baseline:** Ensure the alignment is mathematically tied to the highway centerline stationing and postmile limits.
                        """
                    )
                st.markdown("---")
                
                # Dynamically construct a highly sophisticated query engineering prompt incorporating the District and Owner
                engineered_question = (
                    f"For a {selected_class} associated with {utility_owner} "
                    f"in Caltrans {selected_district}, identify the applicable "
                    f"Caltrans requirements for encroachment, installation, "
                    f"clearance, location, construction, and protection. "
                    f"Distinguish mandatory requirements from recommendations "
                    f"and identify any requirements that depend on project-specific "
                    f"conditions. Cite the applicable manual sections and pages."
                )

                if supplemental_note:
                    engineered_question += (
                        "\n\nSUPPLEMENTAL ENGINEERING NOTE:\n"
                        + supplemental_note
                        + "\n\nTreat this supplemental note as engineering guidance "
                        "only. Do not present it as a Caltrans requirement unless "
                        "the retrieved authoritative sources independently support it."
                    )
                submit_analysis = st.button("🔬 Search Manuals & Generate Directive")
                if submit_analysis:
                    with st.spinner("Analyzing manuals, regional guidelines, and owner treaties..."):
                        answer, sources = ask_question(engineered_question, k=5, district=selected_district)
                    st.markdown("### 📝 Engineering Directive")
                    st.info(answer)

                    if supplemental_note:
                        st.markdown("### 💡 Supplemental Engineering Note")
                        st.info(supplemental_note)
                    
                    if sources:
                        st.markdown("### 🔍 Verified References")
                        for src in sources:
                            st.caption(f"• **Manual:** {src['source_manual']} | **Section:** {src['section']} | **Page:** {src['page']}\n")
                    
                    # --- DOWNLOAD BUTTON FOR MODE B ---
                    st.markdown("---")
                    photo_report = generate_markdown_report(
                        f"Photo Scanner (Asset: {selected_class} | Owner: {utility_owner} | Region: {selected_district})", 
                        engineered_question, 
                        answer, 
                        sources
                    )
                    st.download_button(
                        label=f"📥 Download {selected_class} ({utility_owner}) Report (.md)",
                        data=photo_report,
                        file_name=f"caltrans_{selected_class}_{utility_owner}_report.md",
                        mime="text/markdown"
                    )
    else:
        st.info("👈 Upload a field image in the sidebar to begin asset verification.")



        # # --- PANEL 3: MASTER REFERENCE SCHEMATIC ---
        # st.markdown("---")
        # with st.expander("🚰 View Master Water Main & Appurtenance Layout Diagram", expanded=False):
        #     st.info("💡 **Pro-Tip:** Right-click the image and select 'Open image in new tab' to view, zoom, and inspect details in full crisp resolution.")
        #     st.image("WaterMain_Diagram.jpeg", caption="Caltrans Standard Water Main Assemblies & Subsurface Details", use_container_width=True)

# ==========================================
# PANEL 3A: GIS REFERENCE MAP
# ==========================================
st.markdown("---")
with st.expander("🗺️ GIS Reference Map", expanded=False):

    st.markdown("#### 🗺️ Mapbox GL Project Alignment Engine")
    st.write(
        "🌐 *Displaying regional map layouts centered over the San Diego District 11 corridor.*"
    )

    # Establish central San Diego coordinates
    sandiego_latitude = 32.7157
    sandiego_longitude = -117.1611

    # Create map DataFrame
    import pandas as pd

    mapbox_df = pd.DataFrame({
        "lat": [sandiego_latitude],
        "lon": [sandiego_longitude],
        "name": ["Caltrans District 11 Base Alignment Center"]
    })

    # Render map
    st.map(
        data=mapbox_df,
        latitude="lat",
        longitude="lon",
        zoom=12,
        use_container_width=True
    )

    st.success(
        "🎯 **San Diego Mapping Interface Active:** "
        "Canvas is clear, stable, and ready for public state utility overlays."
    )

    st.caption(
        "📍 *Panning, zooming, and map interaction are available directly in the map.*"
    )


# ==========================================
# PANEL 3B: ENGINEERING EXHIBITS
# ==========================================
with st.expander("📐 Engineering Exhibits & Reference Materials", expanded=False):

    st.markdown("#### 📐 Caltrans Standard Water Main Assemblies")

    st.info(
        "💡 **Pro-Tip:** Right-click the image and select "
        "'Open image in new tab' to view, zoom, and inspect "
        "blueprint details in full resolution."
    )

    exhibit_path = BASE_DIR / "images" / "WaterMain_Diagram.jpeg"
    if exhibit_path.exists():
        st.image(
            str(exhibit_path),
            caption="Subsurface Appurtenance Cover & Clearance Details",
            use_container_width=True
        )
    else:
        st.info("Engineering exhibit not included in the public repository.")